### PR TITLE
swift 2.3

### PR DESCRIPTION
**Pull request by avalla**
swift 2.3 version

### CODE REVIEW

**Review by candostdagdeviren — CHANGES_REQUESTED** [review]
Example project's build is failing when I try to build in Xcode 8.0. Could you fix also Example project?

**Comment by avalla** [comment]
now the example builds correctly

**Review by candostdagdeviren — APPROVED** [review]
Thanks for fixing Example project.

**Comment by avalla** [comment]
thanks to you 👍

**Comment by Sorix** [comment]
I will be very pleased if you can merge that pull request and mark that build with 0.2.2 version, so we can use 0.2.x branch with Swift 2.3 👍  like that:

`pod 'UIImageViewWithWords', '~> 0.2.1'`

**Pull request merged**
