### PR TITLE
Extension cleanup

### PR DESCRIPTION
**Pull request by BasThomas**
- Using default parameters to remove duplicate methods
- Changed variables to constants where possible
- Infer types where possible

### CODE REVIEW

**Comment by BasThomas** [comment]
?

**Comment by ridvank** [comment]
Sorry for the misunderstanding. However I could not get the diff file which is not understandable. Can you open new pull request?

**Comment by BasThomas** [comment]
You should be able to view the diff under "Files changed" (https://github.com/ridvank/UIImageViewWithWords/pull/3/files). Then, you can just reopen this PR and merge it :)

**Comment by BasThomas** [comment]
👍

**Comment by ridvank** [comment]
Thanks for your effort btw:)

**Pull request merged**
