### PR TITLE
update to swift3

### PR DESCRIPTION
**Pull request by avalla**
Not sure of this change:

```
let start = characters.index(startIndex, offsetBy: r.lowerBound)
let end = characters.index(start, offsetBy: r.upperBound - r.lowerBound)
```

### CODE REVIEW

**Comment by candostdagdeviren** [comment]
I'll take a look at this PR soon.

**Comment by avalla** [comment]
example doesn't works here too :(

**Comment by candostdagdeviren** [comment]
Could you fix the example also in here @avalla ? Then I can take a look at the Swift implementation easily. 🙂

**Comment by avalla** [comment]
done! but it requires a signing profile to build

**Comment by candostdagdeviren** [comment]
I messed up some stuff for this PR. So I migrated library by myself. I'll close this one. Thanks a lot for your effort and time. 👍

**Pull request closed without merging**
